=== Pristzilla/PracticasServiciosSoftware/Practica1/src/main/resources/InsuranceSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.unican.es/ss/InsuranceSchema"
	xmlns:tns="http://www.unican.es/ss/InsuranceSchema"
	elementFormDefault="qualified">
	<!-- DNI -->
	<xs:simpleType name="DNI">
		<xs:restriction base="xs:token">
			<xs:pattern value="\d{8}[A-Z]" />
		</xs:restriction>
	</xs:simpleType>

	<!-- EMAIL -->
	<xs:simpleType name="email">
		<xs:restriction base="xs:string">
			<xs:pattern value="[^@]+@[^\.]+\..+" />
		</xs:restriction>
	</xs:simpleType>

	<!-- VEHICULO -->
	<xs:complexType name="Vehiculo">
		<xs:attribute name="matricula" type="xs:ID"
			use="required"></xs:attribute>
		<xs:attribute name="potencia" type="xs:int"
			use="required"></xs:attribute>
		<xs:attribute name="usoProfesional" type="xs:boolean"
			use="required" />
	</xs:complexType>

	<!-- SEGURO -->
	<xs:complexType name="Seguro" abstract="true">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="vehiculoAsegurado" type="tns:Vehiculo"  />
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
		<xs:attribute name="precio" type="xs:decimal"
			use="required" />
	</xs:complexType>

	<xs:complexType name="Terceros">
		<xs:complexContent>
			<xs:extension base="tns:Seguro">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="TodoRiesgo">
		<xs:complexContent>
			<xs:extension base="tns:Seguro">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="TodoRiesgoFranquicia">
		<xs:complexContent>
			<xs:extension base="tns:Seguro">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<!-- PARTE -->
	<xs:complexType name="Parte">
		<xs:sequence maxOccurs="1" minOccurs="1">
			<xs:element name="seguro" type="xs:IDREF"  />
		</xs:sequence>
		<xs:attribute name="importe" type="xs:decimal"
			use="required" />
		<xs:attribute name="fecha" type="xs:date" use="required" />

	</xs:complexType>

	<!-- CLIENTE -->
	<xs:complexType name="Cliente">
		<xs:sequence>
			<xs:element name="seguros" type="tns:Seguro" maxOccurs="unbounded" />
			<xs:element name="partes" type="tns:Parte" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="nombre" type="xs:string"
			use="required"></xs:attribute>
		<xs:attribute name="email" type="xs:string"
			use="required"></xs:attribute>
		<xs:attribute name="dni" type="tns:DNI" use="required" />
	</xs:complexType>


	<!-- EMPRESA -->
	<xs:complexType name="Empresa">
		<xs:sequence>
			<xs:element name="clientes" type="tns:Cliente"
				maxOccurs="unbounded" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>


	<xs:element name="empresa" type="tns:Empresa" />

</xs:schema>

=== Pristzilla/PracticasServiciosSoftware/Practica1/src/main/resources/InsuranceElements.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:empresa
	xmlns:tns="http://www.unican.es/ss/InsuranceSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.unican.es/ss/InsuranceSchema InsuranceSchema.xsd ">

	<!-- Clientes -->
	<!-- Cliente con 1 seguro a terceros y 1 parte -->
	<tns:clientes dni="12345678A" email="ana@maria.com" nombre="Ana Maria">
		<tns:seguros xsi:type="tns:Terceros" precio="12.2" id="AAA-111111">
			<tns:vehiculoAsegurado matricula="A0443DML" usoProfesional="true" potencia="235" />
		</tns:seguros>
		<tns:partes fecha="2022-01-01" importe="123.04">
			<tns:seguro>AAA-111111</tns:seguro>
		</tns:partes>
	</tns:clientes>
	
	<!-- Cliente con 1 seguro a todo riesgo y 2 partes -->
	<tns:clientes dni="12345678B" email="pepe@castro.com" nombre="Pepe Castro">
		<tns:seguros xsi:type="tns:TodoRiesgo" precio="30.9" id="BBB-222222" >
				<tns:vehiculoAsegurado matricula="D7835AVL" usoProfesional="false" potencia="80" />
		</tns:seguros>
		<tns:partes fecha="2021-03-04" importe="80.35" >
			<tns:seguro>BBB-222222</tns:seguro>
		</tns:partes>
		<tns:partes fecha="2021-06-07" importe="224.60">
			<tns:seguro>BBB-222222</tns:seguro>
		</tns:partes>
	</tns:clientes>
	
	<!-- Cliente con 1 seguro a todo riesgo franquicia y 1 parte -->
	<tns:clientes dni="12345678C" email="isabela@madrigal.com" nombre="Isabela Madrigal">
		<tns:seguros xsi:type="tns:TodoRiesgoFranquicia" precio="40.0" id="CCC-333333">
				<tns:vehiculoAsegurado matricula="A8392KIE" usoProfesional="true" potencia="80" />
		</tns:seguros>
		<tns:partes fecha="2020-05-10" importe="60.80">
			<tns:seguro>CCC-333333</tns:seguro>
		</tns:partes>
	</tns:clientes>
	
	<!-- Cliente con 1 seguro a terceros, 1 seguro a todo riesgo y ningun parte -->
	<tns:clientes dni="12345678D" email="javier@losada.com" nombre="Javier Losada">
		<tns:seguros xsi:type="tns:Terceros" precio="40.0" id="DDD-444444">
				<tns:vehiculoAsegurado matricula="B2718MES" usoProfesional="false" potencia="120" />
		</tns:seguros>
		<tns:seguros xsi:type="tns:TodoRiesgo" precio="20.00" id="EEE-555555">
				<tns:vehiculoAsegurado matricula="R7839KOE" usoProfesional="false" potencia="120" />
		</tns:seguros>
	</tns:clientes>
</tns:empresa>
